server.port=8080

spring.datasource.url=jdbc:mysql://hotel-db.c7qo04ycgurx.ap-south-1.rds.amazonaws.com:3306/hotel_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Root_user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
